[otel]

[otel.metrics_exporter]

[otel.metrics_exporter.otlp-grpc]
endpoint = "https://example.invalid"

[otel.metrics_exporter.otlp-grpc.headers]
example = "example"

[otel.metrics_exporter.otlp-grpc.tls]
ca-certificate = "example"
client-certificate = "example"
client-private-key = "example"
