[tools]

[tools.experimental_request_user_input]
enabled = false

[tools.update_plan]
enabled = false

[tools.web_search]
allowed_domains = ["example"]
context_size = "low"

[tools.web_search.location]
city = "example"
country = "example"
region = "example"
timezone = "example"
